version: 0.2

env:
  variables:
    S3_BUCKET: "aivle22-website"
    BUILD_DIR: "dist"
    CLOUDFRONT_DISTRIBUTION_ID: ""

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Node version:"
      - node -v
      - echo "NPM version:"
      - npm -v

  pre_build:
    commands:
      - echo "Move to frontend directory"
      - cd frontend
      - echo "Install dependencies"
      - npm ci

  build:
    commands:
      - echo "Build frontend"
      - npm run build
      - echo "Check build output"
      - ls -R

  post_build:
    commands:
      - echo "Deploy frontend to S3"
      - aws s3 sync $BUILD_DIR s3://$S3_BUCKET --delete
      - echo "Frontend deployed to S3"

      - |
        if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ]; then
          echo "Invalidate CloudFront cache"
          aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
        else
          echo "No CloudFront distribution id provided. Skipping invalidation."
        fi