version: 0.2

dir: frontend

phases:
  install:
    runtime-versions:
      nodejs: 20

  pre_build:
    commands:
      - npm ci

  build:
    commands:
      # 코드단에서 api 경로를 처리하므로 빈칸으로 수정
      - export VITE_API_URL=""
      - npm run build
  post_build:
    commands:
      - aws s3 sync ./dist s3://aivle22-website --delete
      - aws cloudfront create-invalidation --distribution-id E2633XN9AUHA1I --paths "/*"