version: 0.2

env:
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - cd backend
      - export IMAGE_TAG=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - echo "Login to Amazon ECR"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - echo "Build Spring Boot jar"
      - chmod +x ./gradlew
      - ./gradlew bootJar -x test --no-daemon
      - echo "Build Docker image"
      - docker build -t $ECR_URI:$IMAGE_TAG -t $ECR_URI:latest .

  post_build:
    commands:
      - echo "Push Docker image to ECR"
      - docker push $ECR_URI:$IMAGE_TAG
      - docker push $ECR_URI:latest