# version: 0.2
# phases:
#   build:
#     commands:
#       - cd backend
#       - chmod +x ./gradlew && ./gradlew bootJar -x test --no-daemon
#       - docker build -t aivle22-backend:test .    # 임시 태그, push 안 함

# 아래 내용은 eks 구성 후 반영. 위 내용은 codepipeline 정상동작 확인용으로써 실제 배포되지 않음
version: 0.2

env:
  exported-variables:
    - IMAGE_TAG

phases:
  pre_build:
    commands:
      - cd backend
      - export IMAGE_TAG=${CODEBUILD_RESOLVED_SOURCE_VERSION:0:7}
      - echo "IMAGE_TAG=$IMAGE_TAG"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin $ECR_URI

  build:
    commands:
      - chmod +x ./gradlew
      - ./gradlew bootJar -x test --no-daemon
      - docker build -t $ECR_URI:$IMAGE_TAG .

  post_build:
    commands:
      - docker push $ECR_URI:$IMAGE_TAG