apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deploy          
  namespace: default            
  labels:
    app: backend-deploy
spec:
  replicas: 2                  
  selector:
    matchLabels:
      app: backend-deploy
  template:                      
    metadata:
      labels:
        app: backend-deploy
    spec:
      containers:
      - name: backend-container
        image: 879772956301.dkr.ecr.us-east-2.amazonaws.com/aivle22-backend:latest # 추후 `:latest`를 `:$IMAGE_TAG` 로 변경
        ports:
        - containerPort: 8080    
        envFrom:
        - configMapRef:
            name: backend-config
        - secretRef:
            name: backend-secret
        resources:
          requests:
            cpu: "250m"         
            memory: "512Mi"     
          limits:
            cpu: "500m"       
            memory: "1Gi"      